from srp_filesystem_effects import (
    DATAFRAME_FILE_OPERATIONS,
    DATAFRAME_FILE_PREFIXES,
    FILESYSTEM_OPERATIONS,
    FILESYSTEM_PREFIXES,
)
from srp_interface_effects import (
    AI_OPERATIONS,
    AI_PREFIXES,
    AUTHENTICATION_OPERATIONS,
    AUTHENTICATION_PREFIXES,
    EMAIL_OPERATIONS,
    EMAIL_PREFIXES,
    PRESENTATION_OPERATIONS,
    PRESENTATION_PREFIXES,
)
from srp_network_effects import NETWORK_OPERATIONS, NETWORK_PREFIXES
from srp_persistence_effects import (
    PERSISTENCE_OPERATIONS,
    PERSISTENCE_PREFIXES,
)
from srp_process_effects import PROCESS_OPERATIONS, PROCESS_PREFIXES
from srp_queue_effects import QUEUE_OPERATIONS, QUEUE_PREFIXES

EFFECT_RULES = (
    ("ai", AI_PREFIXES, AI_OPERATIONS),
    ("authentication", AUTHENTICATION_PREFIXES, AUTHENTICATION_OPERATIONS),
    ("email", EMAIL_PREFIXES, EMAIL_OPERATIONS),
    ("filesystem", FILESYSTEM_PREFIXES, FILESYSTEM_OPERATIONS),
    ("filesystem", DATAFRAME_FILE_PREFIXES, DATAFRAME_FILE_OPERATIONS),
    ("network", NETWORK_PREFIXES, NETWORK_OPERATIONS),
    ("persistence", PERSISTENCE_PREFIXES, PERSISTENCE_OPERATIONS),
    ("presentation", PRESENTATION_PREFIXES, PRESENTATION_OPERATIONS),
    ("process", PROCESS_PREFIXES, PROCESS_OPERATIONS),
    ("queue", QUEUE_PREFIXES, QUEUE_OPERATIONS),
)
